### ISSUE TITLE
code format issue tab or spaces

### ISSUE THREAD

**Issue by asmwarrior** [GrieferAtWork/tpp#6]
Hi, I see that there are spaces and tabs in the source code, see the 2 image-shots below: (the source code was shown in the Code::Blocks IDE)

![image](https://github.com/GrieferAtWork/tpp/assets/561818/212a2de1-655b-4350-b455-5f715e4abef8)

and

![image](https://github.com/GrieferAtWork/tpp/assets/561818/a854aeb7-6e9c-4586-a477-16ed565aa46d)

My question is: could it be possible to use all the spaces without any tabs? It looks quite strange that a tab char at the beginning, and a lot of spaces follows later.

Thanks.

**Comment by GrieferAtWork** [comment]
The formating you're seeing is intended and the result of the `.clang-format` config option "UseTab: ForIndentation":

https://github.com/GrieferAtWork/tpp/blob/800e2176b8f33fe67d14a6a1ddb89c4c284890cf/.clang-format#L130

The idea here is to:
- use tabs for indentation
- use space for padding

> My question is: could it be possible to use all the spaces without any tabs? It looks quite strange that a tab char at the beginning, and a lot of spaces follows later.

Sure: do whatever you want with tpp, as long as its allowed by the [license](https://github.com/GrieferAtWork/tpp/blob/800e2176b8f33fe67d14a6a1ddb89c4c284890cf/LICENSE#L1). Other than that, it's not like I could stop you if I wanted to.

But don't expect me to accept pull requests if you're using completely different formating rules (if that's your goal here).
Also: the formatting defined by `.clang-format` isn't exactly what you see in code, so just re-formating will just result in broken output (some day, I'll write my own C code formatter that automatically produces output just the way I like, but until then I usually do most of the formating by hand, and use clang-format as a tool for doing so more quickly).

**Comment by asmwarrior** [comment]
> The idea here is to:
> 
>     * use tabs for indentation
> 
>     * use space for padding

OK, I see, thanks for the explanation.
